# Generated by Django 3.2.5 on 2021-08-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendSetupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(help_text='Start Time', max_length=20)),
                ('end_time', models.CharField(help_text='End Time', max_length=20)),
                ('timezone', models.CharField(help_text='Timezone with UTC format', max_length=10)),
                ('timezone_diff', models.SmallIntegerField(help_text='Timezone difference value')),
                ('currency', models.CharField(help_text='Currency', max_length=10)),
                ('owner_names', models.CharField(help_text='Owner name', max_length=500)),
                ('owner_ssids', models.CharField(help_text='Owner ssid', max_length=300)),
                ('game_names', models.CharField(help_text='Game name', max_length=150)),
                ('game_codes', models.CharField(help_text='Game code', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='Setup create time')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
