# Generated by Django 3.2.5 on 2022-02-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20210825_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuplog',
            name='creator',
            field=models.CharField(default='for_da', help_text='Creator name depends on auth_user', max_length=150),
            preserve_default=False,
        ),
    ]
