# Generated by Django 3.2.5 on 2022-02-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_setuplog_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuplog',
            name='game_names_en',
            field=models.CharField(default='', help_text='Game name', max_length=200),
        ),
    ]
