# Generated by Django 3.2.5 on 2022-04-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_setuplog_game_names_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setuplog',
            name='game_codes',
            field=models.TextField(help_text='Game code'),
        ),
        migrations.AlterField(
            model_name='setuplog',
            name='game_names',
            field=models.TextField(help_text='Game name'),
        ),
    ]
